### ISSUE TITLE
Possible issue with Db.Async.exec throwing instead of returning a Result

### ISSUE THREAD

**Issue by Darkle** [pimbrouwers/Donald#49]
Hi, I seem to be running in to an issue when using `Db.Async.exec` where it seems to be throwing an exception when it encounters an error instead of returning the error in a `Result`. I have created a repo here: https://github.com/Darkle/donald-async-issue and if you run `dotnet restore` then `sqlite3 foo.db ".read ./init-db.sql"` to create the sqlite db, then `dotnet run` you should get the following output:
```
dbResult Ok ()
DB Error: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Asd'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Donald.Db.Async.inner@118-1.MoveNext() in C:\Users\pim\git\Donald\src\Donald\Db.fs:line 119
   at Donald.Db.Async.tryDoAsync@107.MoveNext() in C:\Users\pim\git\Donald\src\Donald\Db.fs:line 110
   at Donald.Db.Async.tryDoAsync@107.MoveNext() in C:\Users\pim\git\Donald\src\Donald\Db.fs:line 113
   at Program.Pipe #4 input at line 32@32.MoveNext() in /home/coop/Coding/scratch/donald-async-issue/Program.fs:line 34
```
You can see that the first one worked and the result is a `Result` of `Ok unit`, but when we do the second db call with a table that doesnt exist, `Db.Async.exec` throws instead of returning the error in a `Result`.

**Comment by sbacquet** [comment]
I think this issue can be closed as fixed (by PR#51)
